### ISSUE TITLE
소마센터 기자재 대여하기

### ISSUE THREAD

**Issue by xme1226** [yebimom/yebimom#10]
아이패드
아이폰 2대
안드로이드 2대 - 갤럭시, 넥서스
서피스

**Comment by xme1226** [comment]
**빌린 것**
아이패드 미니
아이패드
아이폰5S 1개
안드로이드 2개 - 갤럭시, 넥서스
서피스

**Comment by Corikachu** [comment]
추가로 모니터 2대와 데스크탑5대 예전에 빌려둠
