### ISSUE TITLE
안드로이드 로그인 + OAuth2 + API 정하기

### ISSUE THREAD

**Issue by dobestan** [yebimom/yebimom#34]

**Comment by dobestan** [comment]
@Corikachu 이거는 우리가 이번주에 완성을 못했으니깐 각자 API를 사용하는데 django, android에서 알아야하는 부분을 공부해보고, 수요일날 끝내보는걸로 하자.

**Comment by Corikachu** [comment]
안드로이드는 잠시 동결 되었으므로 이 이슈는 닫겠습니다 :)
