### ISSUE TITLE
이미지 필드에 관한 제안 사항

### ISSUE THREAD

**Issue by wikibootup** [yebimom/yebimom#38]
이미지 필드 진행 상황
===
`image field`는 현재 가벼운 `모델 - 폼 - 뷰 - 템플릿` 코드가 만들어져 있습니다.

원래는 모델로만 테스트를 해보려고 했는데 그게 조금 어려운 것 같습니다.

이미지가 설정해둔 경로에(`MEDIA ROOT`) 맞게 업로드 되는지 테스트 하려면 `폼 필드`를 통해서 해야한다고 합니다.
(`Form` 클래스에서만 적용되는 `file field object`를 통해서 만드러진 객체여야 한다고 합니다.)

(해당 자료가 필요하면 문서를 좀 더 찾아보고 공유하겠습니다.)

정리하면
- 현재 테스트 코드는 없고 웹과 쉘로만 테스트를 해보았습니다.
- 웹에는 로컬에서 파일을 선택해 올리는 부분만 구현되어 있습니다. 
- 현재 코드에는 `MEDIA ROOT`가 적용되 있지 않아서 작동을 안합니다.
- 주소는 임시로 `/upload/`에 맞춰놓았습니다. 

제안1. :  Image Field
===
```python
class CenterImage(models.Model):
    image = ProcessedImageField(
        upload_to='',
        processors=[ResizeToFill(100, 50)],
        format='JPEG',
        options={'quality': 60}
    )
```

현재 이미지 필드는 [imagekit](https://github.com/matthewwithanm/django-imagekit/)에 나와 있는 샘플 이미지 필드입니다.

센터에 들어갈 이미지들은 우선 생각하기에 `메인 이미지, 세부 이미지, 썸네일`이 있을 것 같아요.
그래서 이거를 컨텐츠 항목 별로 나눠보려고 합니다. 이런 식으로 나눠보려고 하는데 어떨까요?

(이미지의 사이즈는 바뀔 수 있는 부분이니 크기는 대략 정하려고 합니다)

```python
class CenterMainImage(models.Model):
    center = models.ForeignKey('Center')

    image = ProcessedImageField(
        upload_to=HASHED_CENTER_NAME
        processors=[ResizeToFill(BIG SIZE)],
        ...
    )
    
class CenterSubImage(models.Model):
    center = models.ForeignKey('Center')

    image = ProcessedImageField(
        upload_to=HASHED_CENTER_NAME
        processors=[ResizeToFill(Middle SIZE)],
        ...
    )
    
class CenterThumbImage(models.Model):
    center = models.ForeignKey('Center')

    image = ProcessedImageField(
        upload_to=HASHED_CENTER_NAME
        processors=[ResizeToFill(THUMBNAIL SIZE)],
        ...
    )
```

제안2. 업로드 경로
===
업로드 경로를 `[해시된 센터 이름]/[해시된 센터 이미지 네임]`으로 하면 어떨까요?

제안3. 파일 확장자 및 파일 크기 제한
===
사용자가 올리는 이미지 파일 확장자는 `png`와 `jpg`만 받는게 좋을까요?
여기에 모바일에서 올리는 이미지의 확장자까지 고려해서 확장자를 제한하려고 합니다.

파일 당 크기 제한은 우선은 `10MB`로 정해서 제한해둘까 합니다.

제안4. 테스트 방법
===
이미지 관련 테스트 할 때에는 `MEDIA ROOT`를 수정해서 `로컬에서 하려고 합니다.` 
( `S3`에 업로드하는 테스트도 작성은 해야할 것 같습니다. )

그런데 테스트를 하려면 다운로드하고 업로드 하는 파일들이 필요할텐데 이거를 

- 임시로 생성하고 지워줄지( os 라이브러리를 써서, os 라이브러리를 쓰기 조금 꺼림직하네요 )
- 크기 0의 dummy 이미지 파일을 만들어놓고 지우지 않고 테스트 해볼지 ( 그래도 업로드 된 파일은 지우고 )

어떤게 좋을까요? 더 좋은 방법이 있을까요?

제안5. 폼필드랑 템플릿
===
```python
class CenterImageForm(ModelForm):
    class Meta:
        model = CenterImage
        fields = ['image']
```
위에 코드는 샘플로 적용한 `CenterImage` 모델폼입니다.

- `템플릿`과 `뷰`에서 적용하는 폼은 장고의 폼필드로 만들고,
- `폼 필드`는 모델로부터 상속을 받는 `모델폼`을 사용하면 어떨까요?
 

이 경우에 모델에서 폼필드를 만들면 다른 부분이 가벼워지는 장점이 있을 것 같습니다.

그렇지만 템플릿에서 적용하는 폼은 `장고의 모델 폼`에서 가져온 걸 그대로 쓰기엔 수정이 필요한 부분이 잇을 수 있어서
`템플릿` 코드에서 `{{ form }}`의 형태로 가져다 쓰는게 무리일 수 있을 것 같아요.

**Comment by dobestan** [comment]
> 이미지가 설정해둔 경로에(MEDIA ROOT) 맞게 업로드 되는지 테스트 하려면 폼 필드를 통해서 해야한다고 합니다.

그럼 이렇게 하지 않으면 어디에다가 업로드가 되나요? ( 기본적인 이미지 필드를 사용한다면? )

**Comment by dobestan** [comment]
<제안1. : Image Field> 이거는 현재 구성에서 반대합니다. 동일 모델에 들어가야한다고 생각합니다. 그래서 여러 방법이 있겠지만,

1. 메인 이미지의 경우에는 ( 어차피 1개일 테니깐 ), `센터해쉬/샌터해쉬`로 저장된다.
2. 썸네일 이미지의 경우에는 `ImageSpecField ` 이용해서 진행한다. ( https://github.com/matthewwithanm/django-imagekit/#defining-specs-in-models )

**Comment by darjeeling** [comment]
http://www.elliotbradbury.com/populating-django-imagefield-testing/

**Comment by darjeeling** [comment]
http://stackoverflow.com/questions/4283933/what-is-the-clean-way-to-unittest-filefield-in-django

**Comment by darjeeling** [comment]
http://stackoverflow.com/questions/2473392/unit-testing-a-django-form-with-a-filefield

**Comment by darjeeling** [comment]
http://blog.chipx86.com/2008/07/25/django-tips-pil-imagefield-and-unit-tests/

**Comment by darjeeling** [comment]
http://hustoknow.blogspot.kr/2010/08/test-driven-development-with-django.html

**Comment by wikibootup** [comment]
https://github.com/spulec/moto
