### ISSUE TITLE
제 1주차 제안사항 및 아이디어

### ISSUE THREAD

**Issue by dobestan** [yebimom/yebimom#5]
제 1, 2주차에 진행하고 싶은 사항이나 제안사항들에 대해서 편하게 얘기해주시면 됩니다. 이번 주는 첫 주라서 그냥 1, 2주차를 함께 진행하지만 앞으로는 **N주차에 진행할 내용들은 N-1주차에 확실하게 결정**하고 진행을 하면 좋을 것 같습니다.

**Comment by dobestan** [comment]
1. 약간 리뷰랑은 멀어지는 얘기일 수도 있는데, 사이트에서 리뷰를 볼 수 있도록 하면서 ( 많은 트래픽 발생 ) 예비맘 교실이나 예비맘 강의 등을 연결해주는 모델도 재미있을 것 같아요. 약간은 온오프믹스의 예비맘 교실에 특화된 버전이라고 생각하는데 어떻게 생각하세요

**Comment by dobestan** [comment]
2. 공용 경비를 모아서 도메인 구매 비용 ( 이번에는 @wikibootup 진우형이 부담함 / 나중에 정산처리 ) 이나 서비스 이용 비용 등 재료비에서 쓸 수 없는 비용들을 정산하면 어떨까요?

**Comment by dobestan** [comment]
[제안 3]
사업자등록과 통신판매업 신고를 빠르게 3월 중에 진행하면 어떨까요? 여러가지 이점이 있을 것 같은데, 생각나는 것만 몇 가지 적어보자면,

- [제안 2]에서 나왔던 통장도 개인 명의가 아니라 사업자 명의로 만들 수 있다.
- 사업자 네이버 계정을 만들 수 있다. 그래서 네이버 블로그와 네이버 카페를 운영하자. ( 네이버 블로그와 카페를 빨리 운영을 해서 사용자를 모으는게 중요할 것 같다. )

**Comment by dobestan** [comment]
[제안 4]
멘토링 시간을 제외하고 일주일에 8시간 정도 함께 개발하는 시간이 있었으면 좋겠다. 개인적으로는 수요일 멘토링 시간 전이나 토요일 멘토링 시간 전에도 굉장히 좋을 것 같다.

**Comment by wikibootup** [comment]
@dobestan

**Comment by wikibootup** [comment]
@dobestan 
[제안 1]에 대해서 
일단 되게 재밌고 좋은 아이디어인 것 같습니다. 저도 'yebimom' 사이트가 예비맘과 관련된 프로그램 & 광고 & 서비스로 하나의 허브처럼 되었으면 좋겠습니다. 처음에 모집을 할 때에는 어떤 식으로 연락을 취해보는게 좋을까요? (해당 기관의 전화, e-mail, 웹 사이트 방문 등으로 요청을 드리는 방법을 취하면 될까요?)

[제안 2]에 대해서
가계부 쓰는 것 되게 좋은 것 같습니다. 추가 비용에 대해서는 금액을 분담하고 내역을 기록하는 부분에 있어서 공동 경비를 모아서 가계부를 정리하면 진짜 좋을 것 같습니다.

[제안 3]에 대해서
사업자 네이버 계정 진짜 좋은 것 같습니다. 기존의 터줏대감같은 카페들이 있을텐데, 그 쪽에서 견제를 받을 정도의 위치까지 올라갔으면 좋겠습니다. 그런데 저희 나머지 세명도 사업자 등록을 해야 가능하겠죠?

[제안 4]에 대해서
좋은 것 같습니다. 직접 만나서 같이 하는 것도 좋지만 우선 온라인에서 서로 진행하는 상황에 대해 빠른 피드백이랑 리뷰가 필요할 것 같습니다.

**Comment by dobestan** [comment]
@wikibootup

**Comment by dobestan** [comment]
@wikibootup 

- 사실 광고나 제휴가 가장 효과적일 것 같아요. 이메일은 사실 별로 효과적이지 못한 것 같고. 저도 지금 검색해보면서 자료 조사를 조금 해보고 있습니다.
- 4명이서 전부 사업자 등록을 하는 건 사실 큰 의미가 없구요, 사업자를 하나 만들면 일단 관리자 아이디를 하나 만들 수 있습니다. ( `yebimom` ) 그리고 여기에다가 이제 각자 원래 네이버 계정과 연동을 시킬 수 있는데 이러면 로그인 할 때 `yebimom.dobestan`, `yebimom.wikibootup` 이라는 아이디와 원래 네이버 비밀번호로 로그인 할 수 있습니다. 그리고 블로그를 작성해도 동일인이 작성한 것 처럼 보입니다.

**Comment by xme1226** [comment]
[제안 1]에 대하여
나도 이 부분이 우리 서비스의 강점이자 비즈니스 모델이라고 생각해요.
예비맘에 대한 컨텐츠는 생각보다 많아서 (강의, 육아교실, 문화교실, 필라테스, 요가 등등) 트래픽 확보에 성공하면 그 다음부터 이런 방향으로 모델을 잡는 것도 좋겠다는 생각입니다.

[제안 2]에 대하여
적극 찬성.
그런데 도메인 구매 비용을 재료비에서 쓸 수 없나요?
전 쓸 수 있는걸로 알고있어서요.

[제안 3]에 대하여
이 부분은 내가 잘 몰라서 패스. 미팅에서 논의할게요!

[제안 4]에 대하여
대 찬성!!! 이건 반드시 필요하다고 저도 생각합니다 :):):) 에쎈셜!!!

**Comment by Corikachu** [comment]
[제안1]
다른곳들을 보니 전문가 상담이 있는곳도 있고,  질문답변이 온라인/오프라인으로 이루어 지고 있는경우도 있더라고요. 그런쪽으로 확장시켜 생각하면 좋을것 같아요.

[제안2]
물론 사용하는 경비에 대해서 기록하고 관리하는것은 필요하다고 생각하는데 최대한 재료비에서 처리하고 싶네요. 추가 되는 비용이 있다면 그 때가서 결정해도 늦지 않는다 생각합니다.

[제안3]
좀 더 논의해 보고싶습니다. 사업자등록은 보통 사업이 수익을 내는 시점에서 세금 납부를 위해 등록하는것으로 아는데, 굳이 지금 할 필요가 있나 생각이 듭니다. 예전에 대학생 창업자가 등록후에 국가장학금이 짤렸다는 이야기를 들은적이 있어서요. 예상치 못한 부작용도 생각해 봐야합니다.

[제안4]
대찬성입니다 :+1:
