### ISSUE TITLE
도메인 구입하기 : yebimom.com

### ISSUE THREAD

**Issue by dobestan** [yebimom/yebimom#6]

**Comment by dobestan** [comment]
@wikibootup 도메인 구입하시면 도메인 관리 페이지에서 네임서버 아래 내용으로 변경해주세요.

**Comment by dobestan** [comment]
#4

**Comment by wikibootup** [comment]
@dobestan 현재(2.27 6 PM) 도메인 구매 완료한 상황입니다. 그렇지만 cosmotown.co.kr에서 제공하는 관리 페이지에 이것이 아직 등록이 안되어 해당 사이트에 문의 해놓은 상태입니다. 적용되는 대로 해당 설정(AWS) 적용하도록 하겠습니다.

**Comment by dobestan** [comment]
@wikibootup 완료하시면 이슈 종료 해주세요 :+1:
