### ISSUE TITLE
Repo에 직접 Push 막아두기

### ISSUE THREAD

**Issue by wikibootup** [yebimom/yebimom#7]
사람은 실수를 하게 마련입니다. `git push upstream master`와 같은 실수를 하지 않도록 push 방지를 해놓도록 하겠습니다.

**Comment by dobestan** [comment]
하고 나서 방법도 공유해주세요 :+1:

**Comment by dobestan** [comment]
@wikibootup 어제 내용 혹시 여기나 위키에다가 간단하게 댓글로 남겨주시고, 종료해주시면 :+1:

**Comment by wikibootup** [comment]
https://github.com/yebimom/yebimom/wiki/Github-%EA%B8%B0%EB%8A%A5-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

**Comment by Corikachu** [comment]
+1 깔끔한 정리네요! 멋져요!
